### ISSUE TITLE
handling fadeIn/fadeOut (opacity)

### ISSUE THREAD

**Issue by jaysachs** [thoun/bga-animations#4]
I'd like to see a replacement for dojo fadeIn/fadeOut. Does this seem better done as a separate animation class, or alongside the rotation/scale inside `BgaSlideToAnimation` ? I kind of think the former.

Separate but related is that if you want just a "scale" or a "rotation" transformation, you need to create a `SlideTo`, which is odd, naming-wise. It's really a design question: do you want a small number of specific transformations that you compose with `playParallel`, or just a few that can do multiple transformations (in which case `SlideTo` is probably not the best name) ?

**Comment by thoun** [comment]
You can do you own animations, there is an example of custom made animation in the demo. The PauseAnimation does almost nothing s maybe you can use it, but a custom animation would fit well for this kind of cases.
