### ISSUE TITLE
equivalent to dojo.fx.chain and dojo.fx.combine

### ISSUE THREAD

**Issue by jaysachs** [thoun/bga-animations#6]
dojo's `chain` and `combine` methods return an animation, which allow you to construct complex animation structures. It would be useful to have the same building blocks here. Currently there is `playParallel` and `playSequence` -- but these actually start the animation going. It would be more flexible to have `BgaSequenceAnimation` and `BgaParallelAnimation` classes. Alternatively, direct equivalents of dojo's `combine` and `chain` functions.

**Comment by thoun** [comment]
Something like [cumulated-animations.ts](https://github.com/thoun/bga-animations/blob/main/src/animations/cumulated-animations.ts) ? ;)

**Comment by jaysachs** [comment]
Ah, I see now there is `BgaCumulatedAnimation`, which provides the parallel composition. I suggest using `BgaChainAnimation` or `BgaSequenceAnimation` as the name ("cumulated" is not an English word. Though it's close to "accumulated", that word doesn't imply "sequence" or "parallel", just "grouping"). Just need a `BgaParallel` or `BgaCombination` for the parallel case.

**Comment by thoun** [comment]
Yeah I'm french and sometimes I don't choose the perfect name :)
